### ISSUE TITLE
[M0-Dev] Elección del lenguaje de programación

### ISSUE THREAD

**Issue by Carlos-SE** [joseantonio2001/OlivApp#11]
Buenas @joseantonio2001. Se me ha asignado tu proyecto para realizar el objetivo 2 :) Lo primero que tenemos que poner en común es el lenguaje de programación que se usará en el desarrollo de tú proyecto. Lo podemos debatir por este issue si te parece.

Un saludo! :handshake:

**Comment by joseantonio2001** [comment]
> Buenas @joseantonio2001. Se me ha asignado tu proyecto para realizar el objetivo 2 :) Lo primero que tenemos que poner en común es el lenguaje de programación que se usará en el desarrollo de tú proyecto. Lo podemos debatir por este issue si te parece.
> 
> 
> 
> Un saludo! :handshake: 

Buenas Carlos, pues en principio había pensado en python como lenguaje.

**Comment by Carlos-SE** [comment]
Qué versión de Python estás pensado en utilizar?

**Comment by joseantonio2001** [comment]
> Qué versión de Python estás pensado en utilizar?

Pues suelo usar la 2.7 o la versión 3, puedes usar cualquiera de los dos.

**Comment by Carlos-SE** [comment]
Yo elegiría la 3, ya que sino tengo mal entendido la versión 2.7 de python ya está sin soporte. Una vez en la versión 3, ¿elegirías 3.10 que es la más reciente?

**Comment by joseantonio2001** [comment]
> Yo elegiría la 3, ya que sino tengo mal entendido la versión 2.7 de python ya está sin soporte. Una vez en la versión 3, ¿elegirías 3.10 que es la más reciente?

Okey, me parece bien la 3.10.

**Comment by Carlos-SE** [comment]
:+1:
