### ISSUE TITLE
[M0-Dev] - Clases y enumerados para representar el los datos

### ISSUE THREAD

**Issue by Carlos-SE** [joseantonio2001/OlivApp#13]
Quería saber qué distribución de clases y enumerados tenías en mente para el proyecto.
En principio supongo que la clase `CosechaAnual`, una clase `Predictor` y un enumerado `Mes`, que contenga los meses del año. Si hay alguna otra clase dímelo para que la añada también.

Con esto dicho, si estás de acuerdo con la clase `CosechaAnual`, te agradecería que me indicases qué datos necesita internamente.

Muchas gracias de antemano :+1:

**Comment by joseantonio2001** [comment]
> Quería saber qué distribución de clases y enumerados tenías en mente para el proyecto. En principio supongo que la clase `CosechaAnual`, una clase `Predictor` y un enumerado `Mes`, que contenga los meses del año. Si hay alguna otra clase dímelo para que la añada también.
> 
> Con esto dicho, si estás de acuerdo con la clase `CosechaAnual`, te agradecería que me indicases qué datos necesita internamente.
> 
> Muchas gracias de antemano +1

Perfecto, me parecen correctas esas clases.
Para cosecha anual necesitaria los datos miembros: Evolucion de precios, producción, precipitaciones, y existencias iniciales (esos 4 datos miembros sería un array de double, ya que cada elemento del array contendrá el dato del parámetro en un mes determinado), aparte de esos datos, creo conveniente también un dato miembro llamado precio máximo, otro dato que sea el mes en el que se alcanzó el precio máximo y un dato miembro que sea meses evaluables (ya que por ejemplo si estamos en Junio el sistema va a comparar los meses hasta junio para generar su predicción en base a los meses siguiente).

**Comment by Carlos-SE** [comment]
Aprovechando que python tiene incluido el tipo de objeto diccionario, ¿no sería más conveniente hacer que los datos que has comentado que serían array sean diccionarios con el mes que corresponda como clave?

**Comment by joseantonio2001** [comment]
> Aprovechando que python tiene incluido el tipo de objeto diccionario, ¿no sería más conveniente hacer que los datos que has comentado que serían array sean diccionarios con el mes que corresponda como clave?

Sí, veo esa opción más viable!

**Comment by Carlos-SE** [comment]
¿Hago que todos los atributos sean privados? ¿A qué datos se deberían implementar `getters` y a cuales `setters`?
Muchas gracias!

**Comment by joseantonio2001** [comment]
> ¿Hago que todos los atributos sean privados? ¿A qué datos se deberían implementar `getters` y a cuales `setters`? Muchas gracias!

Sí, los atributos deben ser privados.
Getters debe haber de todos los datos miembros.

**Comment by Carlos-SE** [comment]
De cara a la lectura de datos desde un fichero, como hemos hablado en clase, he supuesto que el formato será el siguiente:
```
<MES> <PRECIO> <PRODUCCION> <PRECIPITACIONES> <EXISTENCIAS_INICIALES>
ENERO    10.0       20000.75     3000.0   1500.25
.
,
,
,
,
```
¿Te parece corercto?

Sii, está perfecto así

**Comment by Carlos-SE** [comment]
También quería comentarte que meses_evaluables va a almacenar sólo hasta el mes que se puede evaluar a no ser que me digas lo contrario :monocle_face: :wine_glass:

**Comment by joseantonio2001** [comment]
> También quería comentarte que meses_evaluables va a almacenar sólo hasta el mes que se puede evaluar a no ser que me digas lo contrario :monocle_face: :wine_glass:  

Lo que tenia pensado en meses_evaluables es que almacene un string/enum del último mes que va a evaluar, por ejemplo si estamos en Junio, el meses_evaluables será Junio, para que luego al hacer bucles, el bucle pueda evaluar desde Enero hasta el mes indicado, en este caso Junio. En plan poner de tope hasta Junio en este caso.

**Comment by Carlos-SE** [comment]
Justo así está implementado :+1:

**Comment by Carlos-SE** [comment]
Sobre la clase que implementa la lógica de negocio, ¿te parece bien que se llame Predictor o prefieres otro nombre? A parte, crearé las funciones con una utilidad mínima porque ya se escapa de los objetivos a alcanzar durante esta entrega. Pero dime qué métodos y funcionalidades tiene. He ledio la documentación y el documento adjunto pero no me ha terminado de quedar claro. Si prefieres lo podemos hablar mañana en clase :call_me_hand:

**Comment by joseantonio2001** [comment]
> Sobre la clase que implementa la lógica de negocio, ¿te parece bien que se llame Predictor o prefieres otro nombre? A parte, crearé las funciones con una utilidad mínima porque ya se escapa de los objetivos a alcanzar durante esta entrega. Pero dime qué métodos y funcionalidades tiene. He ledio la documentación y el documento adjunto pero no me ha terminado de quedar claro. Si prefieres lo podemos hablar mañana en clase 🤙

Predictor me parece bien.
En cuanto a esa clase, ahora mismo se me ocurren como datos miembros, un dato de tipo cosechaAnual que guarde el ano actual, un dato array de tamaño 5 de tipo cosechaAnual que guarde los 5 últimos anos, ya que el sistema compara el ano actual con los 5 últimos anos para elaborar la predicción, y por último un dato miembro que guarde el mes que el sistema  ha calculado que se prevee que el aceite de oliva alcanze su mayor precio de mercado, es decir, que guarde la predicción.
Si te resulta un poco confuso puedo intentar explicartelo mañana mejor en clase.

**Comment by joseantonio2001** [comment]
Oye se me olvidó comentarte, en la clase cosechaAnual vendría bien tener un identifiador del año, por ejemplo un string para poder identificar el año (p.ej: 2017).

Y otra cosilla, el formato de los informes de donde se sacará la información: será el siguiente:
![image](https://user-images.githubusercontent.com/85243896/198529748-8ec5672b-a128-43e0-bcd5-966c3c69e820.png)
Entonces creo que alomejor el constructor daría algún conflicto al extraer los datos ya que no se salta las primeras lineas (1ª linea: identificador del año, 2ª linea: identificadores de los parámetros de la tabla -> Mes    Precio Medio Global[€/t]    Existencis iniciales  Producción   Precipitaciones).

**Comment by Carlos-SE** [comment]
De acuerdo, ahora lo cambio. Disculpa que no haya ido a clase hoy, me he puesto malo 🤒

**Comment by joseantonio2001** [comment]
> De acuerdo, ahora lo cambio. Disculpa que no haya ido a clase hoy, me he puesto malo 🤒

Okey perfecto!
No te preocupes, mejórate💪

**Comment by Carlos-SE** [comment]
Cuando puedas echa un ojo a los últimos commits que mencionan este issue :wink:

**Comment by joseantonio2001** [comment]
> Cuando puedas echa un ojo a los últimos commits que mencionan este issue 😉

Okey, he estado revisando la clase predictor, e imagino que cosechas_anteriores guarda los 5 últimos años y cosecha_pred se referirá al año actual, no??.
Y luego los métodos cargar_predicción lo que hacen es cargar los documentos que contienen los años, no??
Si es así, me parece correcto!
PD: los documentos no son .txt, son .csv que creo que lo he visto escrito en la linea 25 de la clase Predictor.

**Comment by Carlos-SE** [comment]
De acuerdo, luego cambio para que sea con .CSV, hay que cambiar también la clase CosechaAnual.

**Comment by joseantonio2001** [comment]
> De acuerdo, luego cambio para que sea con .CSV, hay que cambiar también la clase CosechaAnual.

Una cosilla esque analizando un poco mejor, no me queda claro si haría falta un constructor para inicializar  el dato miembro de tipo list cosechas_anteriores con las cosechas de 5 años atrás y lo mismo para el año actual. Y luego en vez de year, no sería mejor un dato que de tipo mes(enum) que guarde el mes en el que se prevee el mayor precio?
Y luego una duda los 2 métodos gen_predicción generarán un archivo. ¿El contenido de ambos es el mismo?
Y por último me podrías explicar el funcionamiento de cargar_predicción?
Siento las molestias, esque me esta costando un poco interpretarlo 😅

**Comment by Carlos-SE** [comment]
@joseantonio2001, al estar utiizando el decorador `@dataclass`, el constructor se genera de forma automática, también se especifica que el atributo `cosecha_pred` es nulo, así que no es necesario pasarlo en el constructor (se puede hacer de todas formas).

La forma en la que lo iba a desarrollar era generar un año entero de predicciones en un objeto `CosechaAnual` para luego poder sacar de ahí el mes con mayor precio.

Los dos métodos de generación de predicción, se diferencian en el nombre (por si lo quieres guardar en un archivo con nombre especial o similar) del fichero que los contendrá, esa implementación ya la tienes que hacer tú en los siguientes objetivos, si quieres que quite una démelo saber.

Cargar predicción llama al constructor de `CosechaAnual`, del dato miembro `cosecha_pred` para cargar los datos en dicho objeto. Los datos salen de los métodos `gen_prediccion(...)`.

Déjame saber qué te parece :smile:

**Comment by joseantonio2001** [comment]
> @joseantonio2001, al estar utiizando el decorador `@dataclass`, el constructor se genera de forma automática, también se especifica que el atributo `cosecha_pred` es nulo, así que no es necesario pasarlo en el constructor (se puede hacer de todas formas).
> 
> 
> 
> La forma en la que lo iba a desarrollar era generar un año entero de predicciones en un objeto `CosechaAnual` para luego poder sacar de ahí el mes con mayor precio.
> 
> 
> 
> Los dos métodos de generación de predicción, se diferencian en el nombre (por si lo quieres guardar en un archivo con nombre especial o similar) del fichero que los contendrá, esa implementación ya la tienes que hacer tú en los siguientes objetivos, si quieres que quite una démelo saber.
> 
> 
> 
> Cargar predicción llama al constructor de `CosechaAnual`, del dato miembro `cosecha_pred` para cargar los datos en dicho objeto. Los datos salen de los métodos `gen_prediccion(...)`.
> 
> 
> 
> Déjame saber qué te parece :smile: 

Vale vale ahora entiendo. En principio me parece correcto!👌

**Comment by Carlos-SE** [comment]
🤙
