### ISSUE TITLE
[M0-Dev] Duda sobre el dominio

### ISSUE THREAD

**Issue by Carlos-SE** [joseantonio2001/OlivApp#15]
Quería concretar cuáles van a ser las entidades y objetos valor del proyecto. Para ello necesito saber qué clases de las siguientes son inmutables y cuales implementan la logica de negocio, de entre las siguientes clases:

* CosechaAnual
* Predictor

Si hay alguna clase o módulo más a tener en cuenta déjamelo saber.
También, creo necesario crear un tipo de dato mes, pero bajo mi criterio, no lo considero una entidad.

**Comment by joseantonio2001** [comment]
> Quería concretar cuáles van a ser las entidades y objetos valor del proyecto. Para ello necesito saber qué clases de las siguientes son inmutables y cuales implementan la logica de negocio, de entre las siguientes clases:
> 
> * CosechaAnual
> * Predictor
> 
> Si hay alguna clase o módulo más a tener en cuenta déjamelo saber. También, creo necesario crear un tipo de dato mes, pero bajo mi criterio, no lo considero una entidad.

En cuanto a clase inmutable sería CosechaAnual, y la lógica de negocio la implementa la clase Predictor.

**Comment by Carlos-SE** [comment]
¿Predictor sería inmutable también, o cambiarán sus valores?

**Comment by Carlos-SE** [comment]
En principio, parece que ambos son entidades.

**Comment by joseantonio2001** [comment]
> ¿Predictor sería inmutable también, o cambiarán sus valores?

Sí, perdón, predictivo también es inmutable.

**Comment by joseantonio2001** [comment]
> ¿Predictor sería inmutable también, o cambiarán sus valores?

Predictor sería mutable.
