### ISSUE TITLE
[M0-Dev] Problema con la representación de las cosechas

### ISSUE THREAD

**Issue by Carlos-SE** [joseantonio2001/OlivApp#17]
Para poder avanzar en #16, necesitamos poder representar las cosechas y todo lo que estas incluyen.  

- ¿Qué es una cosecha? Una cosecha va a ser el conjunto de datos relacionados con la recoleccción de olivas en cada mes y otros datos globales
- ¿Qué datos necesita? En el issue #13  se discute qué datos debe representar.

**Comment by JJ** [comment]
Por favor, mirad [estos errores frecuentes](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-08.md#objetivo-2).
No propongáis estructuras. Plantead el problema de usar un objeto del dominio del problema con la lógica de negocio.

**Comment by Carlos-SE** [comment]
@JJ el indicar la estructura ha sido por aclarar la discursión del issue #13.

**Comment by JJ** [comment]
No puedes aclarar una estructura si no sabes qué problema hay planteado. Si quieres "aclarar" la discusión, crea un issue donde se planteen los problemas de esa discusión (o varios). Y luego propón código, que es lo único que tienes que proponer.
Os recuerdo que este issue va de modelizar el dominio del problema.

**Comment by Carlos-SE** [comment]
> No puedes aclarar una estructura si no sabes qué problema hay planteado. Si quieres "aclarar" la discusión, crea un issue donde se planteen los problemas de esa discusión (o varios). Y luego propón código, que es lo único que tienes que proponer. Os recuerdo que este issue va de modelizar el dominio del problema.

¿Así quedaría mejor? Porque veo que es un objeto que se relaciona con `Predictor`, que es el foco principal del dominio, de forma que surge el problema de crear esta clase.

**Comment by JJ** [comment]
¿Te parece que "necesitamos una clase con nombre X" esté planteando un problema?

**Comment by Carlos-SE** [comment]
Plantea una necesidad

**Comment by JJ** [comment]
Vamos a ver, Carlos. Dices:

> Para poder avanzar en https://github.com/joseantonio2001/OlivApp/issues/16, necesitamos una clase CosechaAnual

¿Te parece que esto sea un problema? ¿O simplemente está diciendo que necesitas algo que es una (1) clase, y que se tiene que llamar de esa forma? Luego dices

> Esta clase es la encargada de representar los datos relacionados con la cosecha de olivos durante un año.

¿Esto qué problema es? Problema sería si trataras de modelizar una cosecha de forma que se pueda atacar con la lógica de negocio. Es decir, ¿qué es una cosecha? ¿Das por sentado que todo el mundo sabe lo que es una cosecha? ¿Una clase que se llame "Cosecha" representa una cosecha? ¿Con eso hemos resuelto el problema?

**Comment by Carlos-SE** [comment]
Ahora diría que representa de forma clara un problema.

**Comment by JJ** [comment]
No, simplemente lo traslada al #13.
