### ISSUE TITLE
[M0-Dev] Problema con la representación de los meses del año

### ISSUE THREAD

**Issue by Carlos-SE** [joseantonio2001/OlivApp#18]
Para avanzar con el `issue` #17, se necesita un enumerado que represente los meses del año.

**Comment by JJ** [comment]
Esto no es modelar un problema. ¿Por qué se necesita un enumerado?
Se trata de que planteéis problemas, no que pongáis tareas.

**Comment by Carlos-SE** [comment]
Es un problema que surge a la hora de diseñar la clase `CosechaAnual`. Debido a que debe contener los datos por meses, pensé que la representación de los mismos era un problema y por eso creé este issue

**Comment by JJ** [comment]
En ese caso, el título y el contenido del issue tienen que dedicarse a formular ese problema, no directamente a "solucionarlo" proponiendo un Enum

**Comment by Carlos-SE** [comment]
> En ese caso, el título y el contenido del issue tienen que dedicarse a formular ese problema, no directamente a "solucionarlo" proponiendo un Enum

De acuerdo, muchas gracias por la aclaración :blush:
